image: ubuntu

before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_production:
    environment:
        name: production
    script:
        - ssh -p $PORT $USER@$IP_HOST "cd public_html/_www/thp &&
            git checkout main &&
            git pull origin main &&
            php artisan migrate &&
            exit"
    only:
        - main
